sudo: true

services:
  - docker

cache:
  directories:
  - $HOME/sources
  - $HOME/output

# language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      # We use gcc inside container
      # - gcc-4.8
      # - g++-4.8

before_install:
  - TAR_DIR=$HOME/sources ./grte/download.sh
  - docker pull ubuntu:14.04

#install:
#  - ./install-lrte.sh

script:
  # Just build lrte in this stage.
  - ./release.py --docker_image=ubuntu:14.04 --no_build_crosstool --output=$HOME/output --upstream_source=$HOME/sources

notifications:
  email: false
